# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\new_ui.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")

        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")

        self.displayLabel = QtWidgets.QLabel(self.centralwidget)
        self.displayLabel.setObjectName("displayLabel")
        self.displayLabel.setAlignment(QtCore.Qt.AlignRight)
        self.displayLabel.setStyleSheet("fontsize:20px")
        self.verticalLayout.addWidget(self.displayLabel)
        
        self.horizontalLayout1 = QtWidgets.QHBoxLayout()
        self.horizontalLayout1.setObjectName("horizontalLayout1")

        self.btnLarge = QtWidgets.QPushButton(self.centralwidget)
        self.btnLarge.setObjectName("btnLarge")
        self.btnLarge.setFixedSize(210,50)

        self.horizontalLayout1.addWidget(self.btnLarge)

        self.btn1_2 = QtWidgets.QPushButton(self.centralwidget)
        self.btn1_2.setObjectName("btn1_2")
        self.btn1_2.setFixedSize(100,50)
        self.horizontalLayout1.addWidget(self.btn1_2)

        self.btn1_3 = QtWidgets.QPushButton(self.centralwidget)
        self.btn1_3.setObjectName("btn1_3")
        self.btn1_3.setFixedSize(100,50)
        self.horizontalLayout1.addWidget(self.btn1_3)

        self.btn1_4 = QtWidgets.QPushButton(self.centralwidget)
        self.btn1_4.setObjectName("btn1_4")
        self.btn1_4.setFixedSize(100,50)
        self.horizontalLayout1.addWidget(self.btn1_4)

        self.btn1_5 = QtWidgets.QPushButton(self.centralwidget)
        self.btn1_5.setObjectName("btn1_5")
        self.btn1_5.setFixedSize(100,50)
        self.horizontalLayout1.addWidget(self.btn1_5)

        self.btn1_6 = QtWidgets.QPushButton(self.centralwidget)
        self.btn1_6.setObjectName("btn1_6")
        self.btn1_6.setFixedSize(100,50)
        self.horizontalLayout1.addWidget(self.btn1_6)

        self.verticalLayout.addLayout(self.horizontalLayout1)

        self.horizontalLayout2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout2.setObjectName("horizontalLayout2")

        self.btn2_1 = QtWidgets.QPushButton(self.centralwidget)
        self.btn2_1.setObjectName("btn2_1")
        self.btn2_1.setFixedSize(100,50)
        self.horizontalLayout2.addWidget(self.btn2_1)

        self.btn2_2 = QtWidgets.QPushButton(self.centralwidget)
        self.btn2_2.setObjectName("btn2_2")
        self.btn2_2.setFixedSize(100,50)
        self.horizontalLayout2.addWidget(self.btn2_2)

        self.btn2_3 = QtWidgets.QPushButton(self.centralwidget)
        self.btn2_3.setObjectName("btn2_3")
        self.btn2_3.setFixedSize(100,50)
        self.horizontalLayout2.addWidget(self.btn2_3)

        self.btn2_4 = QtWidgets.QPushButton(self.centralwidget)
        self.btn2_4.setObjectName("btn2_4")
        self.btn2_4.setFixedSize(100,50)
        self.horizontalLayout2.addWidget(self.btn2_4)

        self.btn2_5 = QtWidgets.QPushButton(self.centralwidget)
        self.btn2_5.setObjectName("btn2_5")
        self.btn2_5.setFixedSize(100,50)
        self.horizontalLayout2.addWidget(self.btn2_5)

        self.btn2_6 = QtWidgets.QPushButton(self.centralwidget)
        self.btn2_6.setObjectName("btn2_6")
        self.btn2_6.setFixedSize(100,50)
        self.horizontalLayout2.addWidget(self.btn2_6)

        self.btn2_7 = QtWidgets.QPushButton(self.centralwidget)
        self.btn2_7.setObjectName("btn2_7")
        self.btn2_7.setFixedSize(100,50)
        self.horizontalLayout2.addWidget(self.btn2_7)

        self.verticalLayout.addLayout(self.horizontalLayout2)

        
        self.horizontalLayout3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout3.setObjectName("horizontalLayout3")

        self.btn3_1 = QtWidgets.QPushButton(self.centralwidget)
        self.btn3_1.setObjectName("btn3_1")
        self.btn3_1.setFixedSize(100,50)
        self.horizontalLayout3.addWidget(self.btn3_1)

        self.btn3_2 = QtWidgets.QPushButton(self.centralwidget)
        self.btn3_2.setObjectName("btn3_2")
        self.btn3_2.setFixedSize(100,50)
        self.horizontalLayout3.addWidget(self.btn3_2)

        self.btn3_3 = QtWidgets.QPushButton(self.centralwidget)
        self.btn3_3.setObjectName("btn3_3")
        self.btn3_3.setFixedSize(100,50)
        self.horizontalLayout3.addWidget(self.btn3_3)

        self.btn3_4 = QtWidgets.QPushButton(self.centralwidget)
        self.btn3_4.setObjectName("btn3_4")
        self.btn3_4.setFixedSize(100,50)
        self.horizontalLayout3.addWidget(self.btn3_4)

        self.btn3_5 = QtWidgets.QPushButton(self.centralwidget)
        self.btn3_5.setObjectName("btn3_5")
        self.btn3_5.setFixedSize(100,50)
        self.horizontalLayout3.addWidget(self.btn3_5)

        self.btn3_6 = QtWidgets.QPushButton(self.centralwidget)
        self.btn3_6.setObjectName("btn3_6")
        self.btn3_6.setFixedSize(100,50)
        self.horizontalLayout3.addWidget(self.btn3_6)

        self.btn3_7 = QtWidgets.QPushButton(self.centralwidget)
        self.btn3_7.setObjectName("btn3_7")
        self.btn3_7.setFixedSize(100,50)
        self.horizontalLayout3.addWidget(self.btn3_7)

        self.verticalLayout.addLayout(self.horizontalLayout3)

        
        self.horizontalLayout4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout4.setObjectName("horizontalLayout4")

        self.btn4_1 = QtWidgets.QPushButton(self.centralwidget)
        self.btn4_1.setObjectName("btn4_1")
        self.btn4_1.setFixedSize(100,50)
        self.horizontalLayout4.addWidget(self.btn4_1)

        self.btn4_2 = QtWidgets.QPushButton(self.centralwidget)
        self.btn4_2.setObjectName("btn4_2")
        self.btn4_2.setFixedSize(100,50)
        self.horizontalLayout4.addWidget(self.btn4_2)

        self.btn4_3 = QtWidgets.QPushButton(self.centralwidget)
        self.btn4_3.setObjectName("btn4_3")
        self.btn4_3.setFixedSize(100,50)
        self.horizontalLayout4.addWidget(self.btn4_3)

        self.btn4_4 = QtWidgets.QPushButton(self.centralwidget)
        self.btn4_4.setObjectName("btn4_4")
        self.btn4_4.setFixedSize(100,50)
        self.horizontalLayout4.addWidget(self.btn4_4)

        self.btn4_5 = QtWidgets.QPushButton(self.centralwidget)
        self.btn4_5.setObjectName("btn4_5")
        self.btn4_5.setFixedSize(100,50)
        self.horizontalLayout4.addWidget(self.btn4_5)

        self.btn4_6 = QtWidgets.QPushButton(self.centralwidget)
        self.btn4_6.setObjectName("btn4_6")
        self.btn4_6.setFixedSize(100,50)
        self.horizontalLayout4.addWidget(self.btn4_6)

        self.btn4_7 = QtWidgets.QPushButton(self.centralwidget)
        self.btn4_7.setObjectName("btn4_7")
        self.btn4_7.setFixedSize(100,50)
        self.horizontalLayout4.addWidget(self.btn4_7)

        self.verticalLayout.addLayout(self.horizontalLayout4)

        self.horizontalLayout5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout5.setObjectName("horizontalLayout5")

        self.btn5_1 = QtWidgets.QPushButton(self.centralwidget)
        self.btn5_1.setObjectName("btn5_1")
        self.btn5_1.setFixedSize(100,50)
        self.horizontalLayout5.addWidget(self.btn5_1)

        self.btn5_2 = QtWidgets.QPushButton(self.centralwidget)
        self.btn5_2.setObjectName("btn5_2")
        self.btn5_2.setFixedSize(100,50)
        self.horizontalLayout5.addWidget(self.btn5_2)

        self.btn5_3 = QtWidgets.QPushButton(self.centralwidget)
        self.btn5_3.setObjectName("btn5_3")
        self.btn5_3.setFixedSize(100,50)
        self.horizontalLayout5.addWidget(self.btn5_3)

        self.btn5_4 = QtWidgets.QPushButton(self.centralwidget)
        self.btn5_4.setObjectName("btn5_4")
        self.btn5_4.setFixedSize(100,50)
        self.horizontalLayout5.addWidget(self.btn5_4)

        self.btn5_5 = QtWidgets.QPushButton(self.centralwidget)
        self.btn5_5.setObjectName("btn5_5")
        self.btn5_5.setFixedSize(100,50)
        self.horizontalLayout5.addWidget(self.btn5_5)

        self.btn5_6 = QtWidgets.QPushButton(self.centralwidget)
        self.btn5_6.setObjectName("btn5_6")
        self.btn5_6.setFixedSize(100,50)
        self.horizontalLayout5.addWidget(self.btn5_6)

        self.btn5_7 = QtWidgets.QPushButton(self.centralwidget)
        self.btn5_7.setObjectName("btn5_7")
        self.btn5_7.setFixedSize(100,50)
        self.horizontalLayout5.addWidget(self.btn5_7)

        self.verticalLayout.addLayout(self.horizontalLayout5)
        

        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Main   Window"))
        self.btnLarge.setText(_translate("MainWindow", "Rad | Deg"))
        self.btn1_2.setText(_translate("MainWindow", "x!"))
        self.btn1_3.setText(_translate("MainWindow", "("))
        self.btn1_4.setText(_translate("MainWindow", ")"))
        self.btn1_5.setText(_translate("MainWindow", "%"))
        self.btn1_6.setText(_translate("MainWindow", "AC"))

        self.btn2_1.setText(_translate("MainWindow", "Inv"))
        self.btn2_2.setText(_translate("MainWindow", "sin"))
        self.btn2_3.setText(_translate("MainWindow", "ln"))
        self.btn2_4.setText(_translate("MainWindow", "7"))
        self.btn2_5.setText(_translate("MainWindow", "8"))
        self.btn2_6.setText(_translate("MainWindow", "9"))
        self.btn2_7.setText(_translate("MainWindow", "÷"))

        self.btn3_1.setText(_translate("MainWindow", "π"))
        self.btn3_2.setText(_translate("MainWindow", "cos"))
        self.btn3_3.setText(_translate("MainWindow", "log"))
        self.btn3_4.setText(_translate("MainWindow", "4"))
        self.btn3_5.setText(_translate("MainWindow", "5"))
        self.btn3_6.setText(_translate("MainWindow", "6"))
        self.btn3_7.setText(_translate("MainWindow", "x"))

        self.btn4_1.setText(_translate("MainWindow", "e"))
        self.btn4_2.setText(_translate("MainWindow", "tan"))
        self.btn4_3.setText(_translate("MainWindow", "√"))
        self.btn4_4.setText(_translate("MainWindow", "1"))
        self.btn4_5.setText(_translate("MainWindow", "2"))
        self.btn4_6.setText(_translate("MainWindow", "3"))
        self.btn4_7.setText(_translate("MainWindow", "-"))

        self.btn5_1.setText(_translate("MainWindow", "Ans"))
        self.btn5_2.setText(_translate("MainWindow", "EXP"))
        self.btn5_3.setText(_translate("MainWindow", "x^y"))
        self.btn5_4.setText(_translate("MainWindow", "0"))
        self.btn5_5.setText(_translate("MainWindow", "."))
        self.btn5_6.setText(_translate("MainWindow", "="))
        self.btn5_7.setText(_translate("MainWindow", "+"))
